// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1uruhoDRmEni5Icrq6_AAh7W2KrGrIPA',
    appId: '1:80445007326:web:bcc1f049a1c0e0b590e94f',
    messagingSenderId: '80445007326',
    projectId: 'asru-chat-app-1234',
    authDomain: 'asru-chat-app-1234.firebaseapp.com',
    storageBucket: 'asru-chat-app-1234.firebasestorage.app',
    measurementId: 'G-5NHJXLYR6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Y5YQ0FgyFHCJm23R7uG03K5pk7ViFg4',
    appId: '1:80445007326:android:e774b3ae2f2a224190e94f',
    messagingSenderId: '80445007326',
    projectId: 'asru-chat-app-1234',
    storageBucket: 'asru-chat-app-1234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxiPywpeHKp4Q7cz9g-znBUPtpCVOkB-I',
    appId: '1:80445007326:ios:6b9a613d11f710fb90e94f',
    messagingSenderId: '80445007326',
    projectId: 'asru-chat-app-1234',
    storageBucket: 'asru-chat-app-1234.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxiPywpeHKp4Q7cz9g-znBUPtpCVOkB-I',
    appId: '1:80445007326:ios:6b9a613d11f710fb90e94f',
    messagingSenderId: '80445007326',
    projectId: 'asru-chat-app-1234',
    storageBucket: 'asru-chat-app-1234.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1uruhoDRmEni5Icrq6_AAh7W2KrGrIPA',
    appId: '1:80445007326:web:e7f4cc272848df5190e94f',
    messagingSenderId: '80445007326',
    projectId: 'asru-chat-app-1234',
    authDomain: 'asru-chat-app-1234.firebaseapp.com',
    storageBucket: 'asru-chat-app-1234.firebasestorage.app',
    measurementId: 'G-MKYK394VDN',
  );

}